### ISSUE TITLE
Compilation issue on 20.04

### ISSUE THREAD

**Issue by xepost** [SYSU-STAR/RACER#5]
Hi ,

I go ahead  with the recommendation of  "-std=c++14"  change in the cmakes, and installed  dw.  All is  compiling other than lkh_tsp_solver  and lkh_mtsp_solver.  I am getting the following error.

`usr/bin/ld: CMakeFiles/lkh_tsp_solver.dir/src/SolveCompressedSubproblem.c.o:(.bss+0xa0): multiple definition of PatchingCExtended; CMakeFiles/lkh_tsp_solver.dir/src/Activate.c.o:(.bss+0xa0): first defined here
/usr/bin/ld: CMakeFiles/lkh_tsp_solver.dir/src/SolveCompressedSubproblem.c.o:(.bss+0xa4): multiple definition of PatchingARestricted; CMakeFiles/lkh_tsp_solver.dir/src/Activate.c.o:(.bss+0xa4): first defined here
/usr/bin/ld: CMakeFiles/lkh_tsp_solver.dir/src/SolveCompressedSubproblem.c.o:(.bss+0xa8): multiple definition of PatchingAExtended; CMakeFiles/lkh_tsp_solver.dir/src/Activate.c.o:(.bss+0xa8): first defined here
/usr/bin/ld: CMakeFiles/lkh_tsp_solver.dir/src/SolveCompressedSubproblem.c.o:(.bss+0xac): multiple definition of MoorePartitioning; CMakeFiles/lkh_tsp_solver.dir/src/Activate.c.o:(.bss+0xac): first defined here
/usr/bin/ld: CMakeFiles/lkh_tsp_solver.dir/src/SolveCompressedSubproblem.c.o:(.bss+0xb0): multiple definition of KMeansPartitioning; CMakeFiles/lkh_tsp_solver.dir/src/Activate.c.o:(.bss+0xb0): first defined here`

I tried to compile the LKH-3.0.6 and I get the same error. Also checked  LKH-3.0.5, which also does not compile on  Ubuntu20.04,  LKH-3.0.7 and LKH-3.0.8 compiles but there are some changes on the APIs, so not sure how to add that part.  

I did  take a look at FUEL repo, but did not see much information other than the ones Known Issues part.  Any recommendations?

**Comment by xepost** [comment]
I solved it by downgrading to gcc/g++9, I was using gcc/g++ 11. Please feel free to close.
